# Generated by Django 4.1.3 on 2022-11-17 11:06

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admin_usr_nm', models.CharField(max_length=50)),
                ('admin_pwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin_tbl',
            },
        ),
        migrations.CreateModel(
            name='AdvancedSummary',
            fields=[
                ('adv_summary', models.BigAutoField(primary_key=True, serialize=False)),
                ('adv_summary_text', models.TextField()),
                ('adv_summary_approval_status', models.BooleanField(default=False)),
                ('adv_summary_approved_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'adv_summary',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notifID', models.BigAutoField(primary_key=True, serialize=False)),
                ('notificationAddedby', models.CharField(max_length=50)),
                ('noticationsMSG', models.TextField()),
                ('notificationSentTo', models.CharField(max_length=50)),
                ('notificationTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('noticatinosView', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
            options={
                'db_table': 'notifications_table',
            },
        ),
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_Name', models.CharField(max_length=50)),
                ('user_DOB', models.CharField(max_length=50)),
                ('user_Gender', models.BooleanField(default=False)),
                ('user_Email', models.EmailField(max_length=254)),
                ('user_Mobile', models.CharField(max_length=10)),
                ('user_UserName', models.CharField(max_length=50)),
                ('user_PWD', models.CharField(max_length=250)),
                ('user_is_Active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_tbl',
            },
        ),
        migrations.CreateModel(
            name='TranslationsModel',
            fields=[
                ('transID', models.BigAutoField(primary_key=True, serialize=False)),
                ('transLang', models.CharField(max_length=20)),
                ('transText', models.CharField(max_length=500)),
                ('transDoneAt', models.DateTimeField(auto_now_add=True)),
                ('transApprovalStatus', models.BooleanField(default=False)),
                ('transApprovedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.adminmodel')),
                ('transDoneBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.user_model')),
            ],
            options={
                'db_table': 'transactions_table',
            },
        ),
        migrations.CreateModel(
            name='SummaryModel',
            fields=[
                ('summary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summary_text', models.CharField(max_length=500)),
                ('summary_org_file', models.TextField()),
                ('summary_author', models.CharField(max_length=50)),
                ('summary_timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary_approval_status', models.BooleanField(default=False)),
                ('summary_advance_available', models.BooleanField(default=False)),
                ('adv_summary_PK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.advancedsummary')),
                ('summary_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.user_model')),
                ('summary_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.adminmodel')),
            ],
            options={
                'db_table': 'summary_tbl',
            },
        ),
        migrations.AddField(
            model_name='advancedsummary',
            name='adv_summaryTextID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.summarymodel'),
        ),
        migrations.AddField(
            model_name='advancedsummary',
            name='adv_summary_added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.user_model'),
        ),
        migrations.AddField(
            model_name='advancedsummary',
            name='adv_summary_approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.adminmodel'),
        ),
    ]
