# Generated by Django 4.1.3 on 2022-11-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedsummary',
            name='adv_summary_added_to_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advancedsummary',
            name='adv_summary_added_to_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='summary_added_to_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summarymodel',
            name='summary_added_to_twitter',
            field=models.BooleanField(default=False),
        ),
    ]
