# Generated by Django 4.1.3 on 2022-11-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_advancedsummary_adv_summary_added_to_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='user_DOB',
        ),
        migrations.RemoveField(
            model_name='user_model',
            name='user_Gender',
        ),
    ]
