# Generated by Django 4.1.3 on 2022-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0003_remove_user_model_user_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='summary_availalabe_trans',
            field=models.BooleanField(default=False),
        ),
    ]
