# Generated by Django 4.1.3 on 2022-11-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0004_summarymodel_summary_availalabe_trans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancedsummary',
            old_name='adv_summary',
            new_name='adv_summary_id',
        ),
    ]
