# Generated by Django 4.1.3 on 2022-11-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0007_alter_advancedsummary_adv_summary_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarymodel',
            name='adv_avaibale_trans',
            field=models.BooleanField(default=False),
        ),
    ]
