# Generated by Django 4.1.3 on 2022-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0008_summarymodel_adv_avaibale_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarymodel',
            name='adv_avaibale_trans',
        ),
        migrations.AddField(
            model_name='advancedsummary',
            name='adv_avaibale_trans',
            field=models.BooleanField(default=False),
        ),
    ]
