# Generated by Django 4.1.3 on 2022-11-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0011_alter_translationsmodel_transapprovedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationsmodel',
            name='transToInsagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationsmodel',
            name='transToTwitter',
            field=models.BooleanField(default=False),
        ),
    ]
