# Generated by Django 4.1.3 on 2023-01-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0015_alter_translationsmodel_transdoneby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarymodel',
            name='summary_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='translationsmodel',
            name='transText',
            field=models.CharField(max_length=5000),
        ),
    ]
