# Generated by Django 4.1.3 on 2023-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0016_alter_summarymodel_summary_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmodel',
            name='approvalStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
    ]
