# Generated by Django 4.1.3 on 2023-02-17 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0017_alter_approvalmodel_approvalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodel',
            name='approval_remaks',
            field=models.TextField(default=datetime.datetime(2023, 2, 17, 5, 19, 17, 633914, tzinfo=datetime.timezone.utc), max_length=500),
            preserve_default=False,
        ),
    ]
