# Generated by Django 4.1.7 on 2023-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0020_alter_contentmodal_contentapproval_remaks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodal',
            name='contentIMGPath',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contentmodal',
            name='content_text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
