# Generated by Django 4.1.7 on 2023-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0022_contentmodal_contentqn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodal',
            name='contentAdded_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
