# Generated by Django 4.1.7 on 2023-03-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0023_alter_contentmodal_contentadded_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAnalysis',
            fields=[
                ('analysis', models.AutoField(primary_key=True, serialize=False)),
                ('twitter_hashtag', models.CharField(max_length=200)),
                ('analysis_ApprovalStatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('analysis_approval_remarks', models.TextField(default='N?A', max_length=500)),
                ('analysis_Added_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('analysis_twitter_path', models.TextField(blank=True, max_length=150, null=True)),
                ('analysis_neutral', models.CharField(blank=True, max_length=20, null=True)),
                ('analysis_positive', models.CharField(blank=True, max_length=20, null=True)),
                ('analysis_negative', models.CharField(blank=True, max_length=20, null=True)),
                ('analysis_very_nagitive', models.CharField(blank=True, max_length=20, null=True)),
                ('analysis_AddedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.user_model')),
                ('analysis_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.adminmodel')),
            ],
            options={
                'db_table': 'twitter_analysis',
            },
        ),
    ]
