# Generated by Django 4.1.7 on 2023-03-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0024_twitteranalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteranalysis',
            old_name='analysis',
            new_name='analysis_id',
        ),
    ]
