# Generated by Django 4.1.7 on 2023-03-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0025_rename_analysis_twitteranalysis_analysis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingConversionModel',
            fields=[
                ('meetingID', models.AutoField(primary_key=True, serialize=False)),
                ('meetingfileLocation', models.CharField(max_length=500)),
                ('meeting_ApprovalStatus', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('meeting_approval_remarks', models.TextField(default='N?A', max_length=500)),
                ('meeting_Added_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('meetinfileChunks', models.CharField(blank=True, default='NOVALUVE', max_length=2000, null=True)),
                ('meetindAddedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.user_model')),
                ('meeting_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='summary.adminmodel')),
            ],
            options={
                'db_table': 'meeting-conversations',
            },
        ),
    ]
