# Generated by Django 4.1.7 on 2023-03-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0026_meetingconversionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingconversionmodel',
            name='meetingTransscription',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
